# Script mode: read a binary file, emit a C byte array.
#
# CMake's hex conversion gives one long string; splitting it into 0x pairs keeps
# the generated header readable and, more importantly, keeps line lengths sane
# for compilers that dislike multi-megabyte single lines.

file(READ "${HELIX_EMBED_IN}" HEX_DATA HEX)
string(LENGTH "${HEX_DATA}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

set(BODY "")
set(COL 0)
set(POS 0)
while(POS LESS HEX_LEN)
    string(SUBSTRING "${HEX_DATA}" ${POS} 2 BYTE)
    string(APPEND BODY "0x${BYTE},")
    math(EXPR COL "${COL} + 1")
    if(COL GREATER_EQUAL 32)
        string(APPEND BODY "\n")
        set(COL 0)
    endif()
    math(EXPR POS "${POS} + 2")
endwhile()

file(WRITE "${HELIX_EMBED_OUT}"
"// Generated by cmake/HelixEmbedRun.cmake. Do not edit.
#include <stddef.h>
extern const unsigned char ${HELIX_EMBED_SYM}[];
extern const size_t        ${HELIX_EMBED_SYM}_len;
const unsigned char ${HELIX_EMBED_SYM}[] = {
${BODY}
};
const size_t ${HELIX_EMBED_SYM}_len = ${BYTE_LEN};
")
